flaskblog/apps/admin/models.py
from ext import db
from werkzeug.security import generate_password_hash, check_password_hash
#
#
# class Admin(db.Model):
#     __tablename__ = 'admin'
#     id = db.Column(db.Integer, primary_key=True)
#     first_name = db.Column(db.String(50), nullable=False)
#     last_name = db.Column(db.String(50), nullable=False)
#     email = db.Column(db.String(50), unique=True)
#     _password = db.Column(db.String(100))
#
#     symptoms = db.relationship('symptom', backref='admin')
#
#     def __repr__(self):
#         return f"User('{self.first_name}', '{self.last_name}')"
#
#     @property
#     def password(self):
#         return self._password
#
#     @password.setter
#     def password(self, pwd):
#         self._password = generate_password_hash(pwd)
#
#     def check_password(self, pwd):
#         return check_password_hash(self.password, pwd)


# class Symptom(db.Model):
#     __tablename__ = 'symptom'
#     id = db.Column(db.Integer, primary_key=True)
#     name = db.Column(db.String(50), nullable=False)
#     date = db.Column(db.Date)
#     time = db.Column(db.Integer)
#     parts = db.Column(db.String(100))
#     degree = db.Column(db.Integer)
#     admin_id = db.Column(db.ForeignKey('admin.id'))
#
#     def __repr__(self):
#         return f"Symptom('{self.name}', '{self.pain_degree}')"

flaskblog/models.py
from datetime import datetime
from ext import db
from flaskblog import login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    _password = db.Column(db.String(60), nullable=False)

    position = db.Column(db.String(50))
    office = db.Column(db.String(50))
    age = db.Column(db.Integer)
    start_date = db.Column(db.Date)
    salary = db.Column(db.String(50))

    posts = db.relationship('Post', backref='author', lazy=True)
    symptoms = db.relationship('Symptom', backref='user')

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.image_file}')"

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, pwd):
        self._password = generate_password_hash(pwd)

    def check_password(self, pwd):
        return check_password_hash(self.password, pwd)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"


# class Symptom(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     name = db.Column(db.String(50))
#     user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
#     duration = db.Column(db.String(50))
#     pain_degree = db.Column(db.Integer)
#     add_time = db.Column(db.Date, default=datetime.today)
#
#     users = db.relationship('User', backref='symptom')
#
#     def __repr__(self):
#         return f"Symptom('{self.name}', '{self.duration}', '{self.pain_degree}')"

class Symptom(db.Model):
    __tablename__ = 'symptom'
    # __table_args__ = {'schema': 'schema_any'}
    # __abstract__ = True
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    date = db.Column(db.Date)
    time = db.Column(db.Integer)
    parts = db.Column(db.String(100))
    degree = db.Column(db.Integer)
    user_id = db.Column(db.ForeignKey('user.id'))

    def __repr__(self):
        return f"Symptom('{self.name}','{self.date}','{self.time}','{self.parts}', '{self.degree}')"

flaskblog/apps/admin/forms.py
from wtforms import Form, StringField, IntegerField
from wtforms.validators import Length, EqualTo, InputRequired, Email


class BaseForm(Form):
    def get_error(self):
        err = ''
        for v in self.errors.values():
            err += v[0]
        return err


class AddSymptomForm(BaseForm):
    date = StringField(validators=[Length(13, 13, 'Timestamp needed !')])
    time = StringField(validators=[Length(1, 1, 'Pain time needed !')])
    name = StringField(validators=[InputRequired('Please input symptoms! ')])
    parts = StringField(validators=[InputRequired('Please input pain part! ')])
    degree = IntegerField(validators=[InputRequired('Please input pain degree! ')])


class RegisterForm(BaseForm):
    first_name = StringField(validators=[InputRequired('Please input your first name !')])
    last_name = StringField(validators=[InputRequired('Please input your last name !')])
    email = StringField(validators=[Email(message='Please input a correct email address !')])
    password = StringField(validators=[Length(6, 18, 'Please set a 6-18 digits password !')])
    confirm = StringField(validators=[EqualTo('password', 'Password and confirm password not consistent !')])


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message='Please input a correct email address !')])
    password = StringField(validators=[Length(6, 18, 'Please input a 6-18 digits password !')])


flaskblog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flaskblog.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                'That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError(
                'That email is taken. Please choose a different one.')


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

flaskblog/__init__.py
from flask import Flask, render_template,request
from ext import db, login_manager, bcrypt
from flaskblog.apps.admin.routes import bp as admin_bp
from .routes import bp as front_bp
import config

app = Flask(__name__)
app.config.from_object(config)
db.init_app(app)
bcrypt.init_app(app)
login_manager.init_app(app)
app.register_blueprint(admin_bp)
app.register_blueprint(front_bp)


login_manager.login_view = 'login'
login_manager.login_message_category = 'info'


# from flaskblog import routes

@app.errorhandler(404)
def page_not_found(e):
    if request.path.startswith('/admin'):
        return render_template('admin/404.html'), 404
    return '<h1>Page Not Found</h1>', 404

flaskblog/apps/admin/__init__.py
from .routes import bp



flaskblog/apps/admin/routes.py
from flask import (Blueprint, render_template,
                   request, session, redirect,
                   url_for, g)
from flaskblog.models import User, Symptom
from .forms import AddSymptomForm, RegisterForm, LoginForm
# from flaskblog.apps.admin.models import Admin

from ext import db
from functools import wraps
import time
import datetime
from restful import success, param_error

bp = Blueprint('admin', __name__, url_prefix='/admin')


@bp.before_request
def before_request():
    user_id = session.get('user_id')
    if user_id:
        user = User.query.get(user_id)
        g.user = user


def login_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if g.get('user'):
            return f(*args, **kwargs)
        return redirect(url_for('front.login'))

    return wrapper


@bp.route('/tables/')
def tables():
    users = User.query.all()
    return render_template('admin/tables.html', users=users)


@bp.route('/patient/', methods=['get', 'post'])
def patient():
    # if request.method == 'POST':
    #     form = AddSymptomForm(request.form)
    #     print(request.form)
    #     print(request.form.getlist('symptom'))
    #     if form.validate():
    #         print('pass validation')
    #         symptom = form.symptom.data
    #         duration = form.duration.data
    #         degree = form.degree.data
    #         parts = form.parts.data
    #         sym = Symptom(name=symptom, duration=duration, degree=degree, parts=parts)
    #         db.session.add(sym)
    #         db.session.commit()
    #         return 'Symptom added successfully! '
    #     else:
    #         print(form.get_error())
    return render_template('admin/patient.html')


@bp.route('/patientlist/')
def patientlist():
    # users = User.query.all()
    from_date = (datetime.datetime.today() - datetime.timedelta(days=14)).date()
    to_date = datetime.datetime.today().date()
    from sqlalchemy import func
    syms = db.session.query(Symptom).filter_by(
        user_id=g.user.id).\
        filter(Symptom.date.between(from_date, to_date)).\
        order_by(Symptom.date).all()
    return render_template('admin/patientlist.html', syms=syms)


@bp.add_app_template_filter
def format(v):
    if v == 1:
        return [1, 0, 0, 0]
    elif v == 2:
        return [0, 2, 0, 0]
    elif v == 3:
        return [0, 0, 3, 0]
    else:
        return [0, 0, 0, 4]


@bp.route('/symptom/', methods=['get', 'post'])
def symptom():
    if request.method == 'POST':
        if not request.form:
            return param_error('Please click Add button to add some new symptoms !')
        date = request.args.get('date')
        duration = request.args.get('time')
        time_array = time.localtime(float(int(date) / 1000))
        date = time.strftime("%Y-%m-%d", time_array)
        date = datetime.datetime.strptime(date, '%Y-%m-%d').date()
        values = [x for x in request.form.values()]
        values_group = [values[i:i + 3] for i in range(0, len(values), 3)]
        for value in values_group:
            name = value[0]
            parts = value[1]
            degree = value[2]
            if not name:
                return param_error('Please input the symptom !')
            sym = Symptom.query.filter_by(name=name).first()
            if sym:
                return param_error('The symptom already exists !')
            sym = Symptom(name=name, date=date, time=int(duration), parts=parts, degree=int(degree), user_id=g.user.id)
            db.session.add(sym)
        db.session.commit()
        return success()
    return render_template('admin/symptom.html')


# @bp.route('/register/', methods=['get', 'post'])
# def register():
#     if request.method == 'POST':
#         form = RegisterForm(request.form)
#         if form.validate():
#             first_name = form.first_name.data
#             last_name = form.last_name.data
#             email = form.email.data
#             if User.query.filter_by(email=email).first():
#                 return 'The email already exists ！'
#             password = form.password.data
#             user = User(first_name=first_name, last_name=last_name, email=email, password=password)
#             db.session.add(user)
#             db.session.commit()
#             session['user_id'] = user.id
#             return redirect(url_for('admin.patient'))
#         return form.get_error()
#     return render_template('register.html')
#
#
# @bp.route('/login/', methods=['get', 'post'])
# def login():
#     if request.method == 'GET':
#         if g.get('user'):
#             return redirect(url_for('admin.patient'))
#         global next_to
#         next_to = request.referrer
#         return render_template('login.html')
#     form = LoginForm(request.form)
#     if form.validate():
#         email = form.email.data
#         password = form.password.data
#         remember = request.form.get('remember')
#         user = User.query.filter_by(email=email).first()
#         if not user:
#             return 'The account is not registered !'
#         if not user.check_password(password):
#             return 'The password is not correct !'
#         session['user_id'] = user.id
#         if remember:
#             session.permanent = True
#         return redirect(next_to) if next_to else redirect(url_for('admin.patient'))
#     return form.get_error()
#
#
# @bp.route('/logout/')
# def logout():
#     session.pop('user_id')
#     return redirect(url_for('front.login'))


@bp.route('/')
@login_required
def index():
    return render_template('admin/index.html')

flaskblog/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from ext import db, bcrypt
from flaskblog.forms import RegistrationForm, LoginForm
from flaskblog.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required


bp = Blueprint('front', __name__)
'''
posts = [
    {
        'author': 'Corey Schafer',
        'title': 'Blog Post 1',
        'content': 'First post content',
        'date_posted': 'April 20, 2018'
    },
    {
        'author': 'Jane Doe',
        'title': 'Blog Post 2',
        'content': 'Second post content',
        'date_posted': 'April 21, 2018'
    }
]
'''


@bp.route("/")
@bp.route("/home/")
def home():
    return render_template('home.html', title='Home Page')


@bp.route("/symptom/")
def symptom():
    return render_template('symptom.html', title='Symptom')


@bp.route("/visualization/")
def visualization():
    return render_template('visualization.html', title='Visualization')


@bp.route("/register/", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('admin.patient'))
    form = RegistrationForm()
    if form.validate_on_submit():
        # hashed_password = bcrypt.generate_password_hash(
        #     form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('front.login'))
    return render_template('register.html', title='Register', form=form)


@bp.add_app_template_filter
def arr(v):
    new_list = []
    for x in v:
        new_list.append([x.name, x.time, x.parts, x.degree, x.date])
    return new_list


@bp.route("/login/", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('admin.patient'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # if user and bcrypt.check_password_hash(user.password, form.password.data):
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('admin.patient'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@bp.route("/logout/")
def logout():
    logout_user()
    return redirect(url_for('front.login'))


@bp.route("/account")
@login_required
def account():
    return render_template('account.html', title='Account')

flaskblog/templates/_macros.html
{% macro static(filename) %}
    {{ url_for('static', filename=filename) }}
{% endmacro %}

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ current_user.username }}</h1>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>Home Page</h1>
    <body>Cancer patients usually receive multiple modalities of treatment, such as surgery,
radiation, and chemotherapy. In addition to damaging cancer cells, radiation and
chemotherapy also damage normal cells in the body, and can give rise to a wide
variety of side effects that overlap in time and space. These side effects include
nausea, body pain, skin changes, loss of sensation, bleeding, and elevated risk of
infection. Accurate recall of the timing and quality of side effects is essential for
oncologists to determine which treatments are poorly tolerated and need change
or re-dosing on an individual basis. However, distorted memory during such a
challenging period of patients lives often precludes thorough relaying of all
complaints at follow-up appointments. Many mobile apps have already been
created to address this problem, by allowing patients to log their daily symptoms
and produce longitudinal summary reports. Yet, these reports can be cumbersome
for physicians to review and then re-narrate (in visually unappealing prose format)
for existing electronic medical record systems.</body>
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Documentation and Sharing of Symptoms - {{ title }}</title>
    {% else %}
        <title>Documentation and Sharing of Symptoms</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Documentation and Sharing of Symptoms</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('front.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('front.symptom') }}">Symptom</a>
              <a class="nav-item nav-link" href="{{ url_for('front.visualization') }}">Visualization</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('front.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('front.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('front.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('front.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>

      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('front.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('front.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/symptom.html
{% extends "layout.html" %}
{% block content %}
    <h1>Symptom Logging</h1>
{% endblock content %}

flaskblog/templates/visualization.html
{% extends "layout.html" %}
{% block content %}
    <h1>Graphs</h1>
{% endblock content %}